//! Generates the `SCHEMA_FILES` list that `src/test_db.rs` includes.
//!
//! `infra/postgres/schema/manifest.txt` is the ordered migration list
//! and the single definition of it. `migrate.sh` reads it at runtime;
//! `TestDb` cannot, because it compiles the SQL in via `include_str!`
//! and `include_str!` needs literal paths at compile time. So this
//! script reads the manifest at *build* time and emits the list as
//! Rust — one definition, two readers, no second copy to keep in step.
//!
//! Before this existed the list was maintained by hand in both places
//! under a sync comment. It drifted (`42-views.sql`, `43-event-facts.sql`
//! reached the manifest and never reached the Rust side, so every
//! DB-backed test ran against a schema missing those tables), which
//! bought it an equality test — and then the equality test meant every
//! migration touched the tail line of two files, so any two migration
//! changes in flight at once collided on merge. Four such collisions in
//! one day is what retired the arrangement. CLAUDE.md §9a: collapse it
//! if you can, pin it with a test if you cannot. This is the collapse.
//!
//! Parsing matches `migrate.sh`'s: strip from `#` on, trim, skip blanks.

use std::path::{Path, PathBuf};

fn main() {
    let crate_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    // crates/core/boss-testing -> repo root
    let schema_dir = crate_dir
        .join("../../../infra/postgres/schema")
        .canonicalize()
        .expect("infra/postgres/schema must exist relative to the crate root");
    let manifest = schema_dir.join("manifest.txt");

    // Adding or removing a schema file changes the directory's mtime;
    // editing manifest.txt changes the file's. Content edits to an
    // individual .sql file need no watch here — the emitted
    // `include_str!` makes rustc itself track each one.
    println!("cargo:rerun-if-changed={}", manifest.display());
    println!("cargo:rerun-if-changed={}", schema_dir.display());
    println!("cargo:rerun-if-changed=build.rs");

    let text = std::fs::read_to_string(&manifest)
        .unwrap_or_else(|e| panic!("reading {}: {e}", manifest.display()));

    let entries: Vec<&str> = text
        .lines()
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter(|l| !l.is_empty())
        .collect();

    // An empty list would load an empty schema into every TestDb and
    // surface as "relation does not exist" a long way from the cause —
    // the exact failure this collapse exists to prevent. Fail loudly at
    // build time instead.
    assert!(
        !entries.is_empty(),
        "{} names no schema files",
        manifest.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from infra/postgres/schema/manifest.txt — do not edit.\n\
         const SCHEMA_FILES: &[(&str, &str)] = &[\n",
    );
    for entry in &entries {
        let path = schema_dir.join(entry);
        // migrate.sh fails by name when the manifest points at a missing
        // file; do the same rather than let include_str! complain about
        // a path inside OUT_DIR.
        assert!(
            path.is_file(),
            "manifest names {entry} but {} does not exist",
            path.display()
        );
        let name = entry.strip_suffix(".sql").unwrap_or(entry);
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("schema_files.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
