//! `TestDb` — per-test Postgres database with the Boss schema loaded.
//!
//! Each `TestDb::new()` call creates a fresh, randomly-named database
//! (`test_boss_<uuid>`), loads the per-module `infra/postgres/schema/`
//! files (the `SCHEMA_FILES` list — generated by `build.rs` from the
//! same ordered manifest `migrate.sh` applies) into it, and returns a
//! connection pool. On `Drop`, the database is dropped via a
//! best-effort background task — if that fails (test process killed,
//! runtime already shut down), the random name prefix makes orphans
//! easy to find and clean up administratively.
//!
//! ## Prerequisites
//!
//! - A reachable Postgres instance with a role that has `CREATEDB`.
//! - The admin URL (connection string pointing at the `postgres`
//!   database or any existing database) via the
//!   `BOSS_TEST_POSTGRES_ADMIN_URL` environment variable, or the default
//!   `postgres://boss:boss@127.0.0.1/postgres`.
//!
//! ## Usage
//!
//! ```ignore
//! #[tokio::test(flavor = "multi_thread")]
//! async fn my_integration_test() {
//!     let db = boss_testing::TestDb::new().await;
//!     sqlx::query("INSERT INTO accounts (id, name) VALUES ($1, $2)")
//!         .bind("account-1")
//!         .bind("Test Account")
//!         .execute(&db.pool)
//!         .await
//!         .unwrap();
//!     // ... exercise code under test against db.pool ...
//! }
//! ```

use std::str::FromStr;

use sqlx::postgres::{PgConnectOptions, PgPool, PgPoolOptions};
use sqlx::{Connection, Executor, PgConnection};
use uuid::Uuid;

const DEFAULT_ADMIN_URL: &str = "postgres://boss:boss@127.0.0.1/postgres";

/// The escape hatch, named so it cannot be set by accident.
const ALLOW_PRODUCTION_ENV: &str = "BOSS_TEST_ALLOW_PRODUCTION_SERVER";

/// Should `TestDb` refuse to run against this server?
///
/// THE INCIDENT THIS EXISTS FOR (2026-08-14). The admin URL defaults to
/// `127.0.0.1`, and a `kubectl port-forward` opened minutes earlier for
/// an unrelated read makes `127.0.0.1` the PRODUCTION cluster database.
/// A `cargo test --workspace` then created 582 scratch databases on the
/// production volume, filled the Longhorn PVC, and crashed Postgres into
/// recovery. It self-recovered in about forty seconds with no data lost
/// — 5,612 jobs, 388,260 audit rows, 24,367 messages all intact — but
/// that was luck, not design.
///
/// The failure is silent and inverted: nothing about running a test
/// suite suggests it will write to production, and the address that
/// makes it dangerous is the same address that makes it correct on a
/// laptop. So host and port cannot distinguish the two, and neither can
/// the database name — both are `postgres`.
///
/// What DOES distinguish them is what else lives on the server. A
/// scratch instance has no reason to hold a database called `boss`;
/// every BOSS deployment does. That single question separates the
/// cluster and boss-gcp (which must never be tested against) from a
/// throwaway `initdb` and from the dev container's sidecar, whose
/// POSTGRES_DB is `postgres`.
///
/// Pure so the decision is testable without a server, which is the
/// whole difficulty with guards like this one.
pub(crate) fn production_refusal(server_has_boss_db: bool, override_set: bool) -> Option<String> {
    if !server_has_boss_db || override_set {
        return None;
    }
    Some(format!(
        "REFUSING to create a test database: this server already hosts a database named \
         `boss`, which means it is a BOSS deployment and not a scratch instance.\n\n\
         TestDb creates a database per test. On 2026-08-14 that ran against the production \
         cluster through a forgotten `kubectl port-forward` — 582 scratch databases, a full \
         volume, and Postgres in recovery. The address is not the tell, because a laptop's \
         own Postgres and a port-forwarded production one are both 127.0.0.1.\n\n\
         Point BOSS_TEST_POSTGRES_ADMIN_URL at a scratch instance (the boss-dev pod's \
         sidecar, or a local `initdb` on a non-standard port), or close the port-forward. \
         If this really is a disposable server that happens to hold a `boss` database, set \
         {ALLOW_PRODUCTION_ENV}=1 and say why in the commit."
    ))
}

// `SCHEMA_FILES: &[(&str, &str)]` — the per-module schema files, in
// manifest apply order, each paired with its SQL. Generated by
// `build.rs` from infra/postgres/schema/*.sql, which is the one
// definition of the list; `migrate.sh` reads the same file at runtime.
// `include_str!` needs a literal path at compile time, which is why the
// build script emits the list rather than `test_db.rs` reading the
// manifest directly. `schema_sql` concatenates the entries so
// `new_without` can skip a module, mirroring migrate.sh's `--without`.
include!(concat!(env!("OUT_DIR"), "/schema_files.rs"));

/// Concatenate the schema files in manifest order, omitting any whose name
/// contains an entry in `without`.
fn schema_sql(without: &[&str]) -> String {
    SCHEMA_FILES
        .iter()
        .filter(|(name, _)| !without.iter().any(|w| name.contains(w)))
        .map(|(_, sql)| *sql)
        .collect::<Vec<_>>()
        .join("\n")
}

pub struct TestDb {
    pub pool: PgPool,
    db_name: String,
    admin_url: String,
}

impl TestDb {
    /// Create a fresh database, load the full Boss schema into it, and
    /// return a pool. Panics on any setup failure — tests that need a
    /// DB can't meaningfully continue without one, so fail loud.
    pub async fn new() -> Self {
        Self::new_with(&[]).await
    }

    /// Like [`new`](Self::new) but omits the schema files whose name
    /// contains any entry in `without` (mirrors migrate.sh's
    /// `--without`). Lets a test prove the core + a subset of modules
    /// bootstrap with, e.g., the ledger absent: `new_without(&["ledger"])`.
    pub async fn new_without(without: &[&str]) -> Self {
        Self::new_with(without).await
    }

    async fn new_with(without: &[&str]) -> Self {
        let admin_url = std::env::var("BOSS_TEST_POSTGRES_ADMIN_URL")
            .unwrap_or_else(|_| DEFAULT_ADMIN_URL.to_string());

        let suffix = Uuid::new_v4().simple().to_string();
        let db_name = format!("test_boss_{}", &suffix[..12]);

        let admin_opts = PgConnectOptions::from_str(&admin_url)
            .unwrap_or_else(|e| panic!("parsing BOSS_TEST_POSTGRES_ADMIN_URL: {e}"));

        let mut admin = PgConnection::connect_with(&admin_opts)
            .await
            .unwrap_or_else(|e| panic!("connecting to admin db at {admin_url}: {e}"));

        // Before creating anything: is this a BOSS deployment? Asked on
        // the admin connection we already hold, so it costs one query
        // and no extra connection.
        let has_boss_db: bool =
            sqlx::query_scalar("SELECT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'boss')")
                .fetch_one(&mut admin)
                .await
                .unwrap_or_else(|e| panic!("probing for a production database: {e}"));
        if let Some(reason) = production_refusal(
            has_boss_db,
            std::env::var(ALLOW_PRODUCTION_ENV).as_deref() == Ok("1"),
        ) {
            panic!("{reason}");
        }

        admin
            .execute(format!(r#"CREATE DATABASE "{db_name}""#).as_str())
            .await
            .unwrap_or_else(|e| panic!("CREATE DATABASE {db_name}: {e}"));

        // Test sessions write audit_log events directly (via
        // PgAuditWriter / seed helpers) without running the projection
        // pipeline that populates the soft-FK parent tables (accounts,
        // vendors, …). The `audit_log_check_refs` BEFORE INSERT trigger
        // would therefore reject every invoice / vendor-invoice event.
        // Disable the check at the DB level — the same escape hatch
        // bundle-import uses (`audit_log.ref_check = 'off'`, see
        // boss-rebuild). The soft-FK *integrity scan*
        // (`check_audit_log_integrity`) runs independently and stays
        // under test.
        admin
            .execute(
                format!(r#"ALTER DATABASE "{db_name}" SET audit_log.ref_check = 'off'"#).as_str(),
            )
            .await
            .unwrap_or_else(|e| panic!("disable ref_check on {db_name}: {e}"));

        // Close admin connection before opening the test DB.
        drop(admin);

        let test_opts = admin_opts.clone().database(&db_name);
        let pool = PgPoolOptions::new()
            .max_connections(5)
            .connect_with(test_opts)
            .await
            .unwrap_or_else(|e| panic!("connecting to test db {db_name}: {e}"));

        let schema = schema_sql(without);
        sqlx::raw_sql(&schema)
            .execute(&pool)
            .await
            .unwrap_or_else(|e| panic!("loading schema into {db_name}: {e}"));

        Self {
            pool,
            db_name,
            admin_url,
        }
    }

    /// Database name, primarily for debugging.
    pub fn name(&self) -> &str {
        &self.db_name
    }
}

impl Drop for TestDb {
    fn drop(&mut self) {
        // Best-effort cleanup. If we're inside a tokio runtime we
        // schedule a background drop of the database. If not, the
        // orphan persists and must be cleaned by `DROP DATABASE
        // test_boss_*` administratively.
        let db_name = std::mem::take(&mut self.db_name);
        let admin_url = std::mem::take(&mut self.admin_url);
        if db_name.is_empty() {
            return;
        }
        if let Ok(handle) = tokio::runtime::Handle::try_current() {
            handle.spawn(async move {
                drop_database(&admin_url, &db_name).await;
            });
        }
    }
}

async fn drop_database(admin_url: &str, db_name: &str) {
    let Ok(opts) = PgConnectOptions::from_str(admin_url) else {
        return;
    };
    let Ok(mut conn) = PgConnection::connect_with(&opts).await else {
        return;
    };
    // Terminate other sessions holding connections to the test db,
    // otherwise DROP DATABASE fails with "database is being accessed
    // by other users". WITH (FORCE) would also work on Postgres 13+.
    let _ = conn
        .execute(
            format!(
                "SELECT pg_terminate_backend(pid) FROM pg_stat_activity \
                 WHERE datname = '{db_name}' AND pid <> pg_backend_pid()"
            )
            .as_str(),
        )
        .await;
    let _ = conn
        .execute(format!(r#"DROP DATABASE IF EXISTS "{db_name}""#).as_str())
        .await;
}

#[cfg(test)]
mod generated_schema_list {
    use super::SCHEMA_FILES;

    /// The generated list must name the manifest's files, in order.
    ///
    /// This used to pin two hand-maintained lists to each other, after
    /// they drifted: `42-views.sql` and `43-event-facts.sql` reached
    /// the manifest and never reached the Rust copy, so every
    /// TestDb-backed test ran against a schema missing those tables.
    /// The failure reads as "relation does not exist" in a test that
    /// has nothing to do with schema loading — a long way from the
    /// cause.
    ///
    /// `build.rs` now generates the list from the schema DIRECTORY, so
    /// that drift is impossible by construction and the old equality
    /// test would be comparing the directory to itself. The test is
    /// kept, repurposed, because generation introduces a *new* failure
    /// the hand-maintained arrangement could not have: a stale or empty
    /// `OUT_DIR` artifact. Reading the directory here at run time means
    /// that if the build script's `rerun-if-changed` coverage ever
    /// regresses, the real schema meets the stale generated list and
    /// this fails — with the same symptom it always guarded against,
    /// caught at the same place.
    #[test]
    fn generated_list_matches_the_schema_directory() {
        let schema_dir =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../infra/postgres/schema");
        let mut expected: Vec<String> = std::fs::read_dir(&schema_dir)
            .unwrap_or_else(|e| panic!("reading {}: {e}", schema_dir.display()))
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_file())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.ends_with(".sql"))
            .collect();
        // Same key as build.rs and migrate.sh's `sort -t- -k1,1n`.
        expected.sort_by_key(|n| {
            let num: u32 = n
                .split('-')
                .next()
                .and_then(|p| p.parse().ok())
                .unwrap_or(u32::MAX);
            (num, n.clone())
        });
        let expected: Vec<String> = expected
            .iter()
            .map(|n| n.trim_end_matches(".sql").to_string())
            .collect();

        let actual: Vec<&str> = SCHEMA_FILES.iter().map(|(name, _)| *name).collect();
        assert!(
            !actual.is_empty(),
            "SCHEMA_FILES is empty — every TestDb would load an empty schema"
        );
        assert_eq!(
            actual, expected,
            "generated SCHEMA_FILES is stale against infra/postgres/schema/*.sql"
        );
    }
}

/// The production guard's decision, exercised without a server —
/// which is the difficulty with guards like this: the dangerous case
/// is precisely the one you must not set up to test.
#[cfg(test)]
mod production_guard {
    use super::{ALLOW_PRODUCTION_ENV, production_refusal};

    #[test]
    fn a_server_holding_a_boss_database_is_refused() {
        let refusal = production_refusal(true, false).expect("a BOSS deployment is refused");
        // The message has to carry the way OUT, not just the way in —
        // the person reading it is mid-suite and needs the next action.
        assert!(refusal.contains("BOSS_TEST_POSTGRES_ADMIN_URL"));
        assert!(refusal.contains(ALLOW_PRODUCTION_ENV));
    }

    #[test]
    fn a_scratch_server_is_allowed() {
        // The dev container's sidecar (POSTGRES_DB=postgres) and a bare
        // `initdb` both land here, which is the point: the guard must
        // not make the safe path harder than the dangerous one.
        assert_eq!(production_refusal(false, false), None);
    }

    #[test]
    fn the_override_is_honoured_but_only_when_explicit() {
        assert_eq!(production_refusal(true, true), None);
        assert!(production_refusal(true, false).is_some());
    }
}
